name: turkcell_project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.4
  # firebase_auth: ^6.1.3
  # firebase_core: ^4.3.0
  # cloud_firestore: ^6.1.1

  go_router: ^17.0.1
  # network manager
  provider: ^6.1.5+1
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8

  phosphor_flutter: ^2.1.0
  flutter_svg: ^2.2.3
  cupertino_icons: ^1.0.8
  pinput: ^6.0.1
  dotted_border: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/assets
